INSERT INTO EMPLOYEE_TYPES (TYPE_EMPLOYEE) VALUES ('FACER');

INSERT INTO EMPLOYEES (NAME, LASTNAME,ID_TYPE_EMPLOYEE, NICKNAME, PASSWORD) VALUES ('JULIAN', 'MARK', 1, 'JMARK', '123');

INSERT INTO OSC (DESCRIPTION) VALUES ('AFULIC');

INSERT INTO LOCATIONS (DESCRIPTION) VALUES ('CORDOBA');

INSERT INTO CAMPAIGN_TYPES (DESCRIPTION) VALUES ('ITINERANCIA');
INSERT INTO CAMPAIGN_TYPES (DESCRIPTION) VALUES ('VIA PUBLICA');
INSERT INTO CAMPAIGN_TYPES (DESCRIPTION) VALUES ('EVENTOS');

INSERT INTO CAMPAIGNS (NAME, TYPE, ID_LOC, ID_OSC, ID_TYPE_CAMPAIGN)
VALUES ('RIO CUARTO', NULL, 1,1,1);

INSERT INTO TEAM_EMPLOYEES (ID_EMPLOYEE, INITIAL_DATE, FINAL_DATE,ID_CAMPAIGN)
VALUES (1, SYSDATE, NULL, 1);

INSERT INTO DONATION (AMOUNT, TYPE_PAY, ID_EMPLOYEE_TEAM)
VALUES (300, 0, (SELECT ID_EMPLOYEE
	FROM TEAM_EMPLOYEES
	WHERE ID = 1));

INSERT INTO DAILY_RECORDS (ID_EMPLOYEE_TEAM, PRODUCTIVE_HOURS, NON_PRODUCTIVE_HOURS, TODAY)
VALUES ((SELECT ID_EMPLOYEE
	FROM TEAM_EMPLOYEES
	WHERE ID = 1), 3, 1, SYSDATE);