CREATE TABLE EMPLOYEE_TYPES
(
ID INT NOT NULL IDENTITY (1,1) PRIMARY KEY,
TYPE_EMPLOYEE VARCHAR (20)
);

CREATE TABLE EMPLOYEES
(
ID INT NOT NULL IDENTITY (1,1) PRIMARY KEY,
NAME VARCHAR (20),
LASTNAME VARCHAR (20),
ID_TYPE_EMPLOYEE INTEGER NOT NULL,
NICKNAME NVARCHAR(20),
PASSWORD NVARCHAR (15)
);

 ALTER TABLE EMPLOYEES
    ADD FOREIGN KEY (ID_TYPE_EMPLOYEE)
    REFERENCES EMPLOYEE_TYPES

