CREATE TABLE EMPLOYEE_TYPES
(
ID INT NOT NULL IDENTITY (1,1) PRIMARY KEY,
TYPE_EMPLOYEE VARCHAR (20)
);

CREATE TABLE OSC
(
ID INT NOT NULL IDENTITY (1,1) PRIMARY KEY,
DESCRIPTION VARCHAR (100)
);

CREATE TABLE LOCATIONS
(
ID INT NOT NULL IDENTITY (1,1) PRIMARY KEY,
DESCRIPTION VARCHAR (30)
);

CREATE TABLE CAMPAIGN_TYPES
(
ID INT NOT NULL IDENTITY (1,1) PRIMARY KEY,
DESCRIPTION VARCHAR (30)
);

CREATE TABLE CAMPAIGNS
(
ID INT NOT NULL IDENTITY (1,1) PRIMARY KEY,
NAME VARCHAR (30),
TYPE VARCHAR (20),
ID_LOC INT,
ID_OSC INT,
ID_TYPE_CAMPAIGN INT
);

CREATE TABLE EMPLOYEES
(
ID INT NOT NULL IDENTITY (1,1) PRIMARY KEY,
NAME VARCHAR (20),
LASTNAME VARCHAR (20),
ID_TYPE_EMPLOYEE INTEGER,
NICKNAME NVARCHAR(20),
PASSWORD NVARCHAR (15)
);

CREATE TABLE TEAM_EMPLOYEES
(
ID INT NOT NULL IDENTITY (1,1) PRIMARY KEY,
ID_EMPLOYEE INT,
INITIAL_DATE DATETIME,
FINAL_DATE DATETIME,
ID_CAMPAIGN INT
);

CREATE TABLE DONATION
(
ID INT NOT NULL IDENTITY (1,1) PRIMARY KEY,
AMOUNT FLOAT,
TYPE_PAY BIT,
ID_EMPLOYEE_TEAM INTEGER
);

CREATE TABLE DAILY_RECORDS
(
ID INT NOT NULL IDENTITY (1,1) PRIMARY KEY,
ID_EMPLOYEE_TEAM INT,
PRODUCTIVE_HOURS FLOAT,
NON_PRODUCTIVE_HOURS FLOAT,
TODAY DATETIME
);
